import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Wrapper from "@/components/hoc/Wrapper";
import AuthProvider from "@/components/hoc/AuthProvider";
import ReduxProvider from "@/redux/provider";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sheryians.",
  description: "Generated by create Sheryians.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ReduxProvider>
          <Wrapper>
            <AuthProvider>
              {children}
              <ToastContainer />
            </AuthProvider>
          </Wrapper>
        </ReduxProvider>
      </body>
    </html>
  );
}